language: php 

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.0

notifications:
  email: qp2624@163.com
   
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

script:
    - exit 0
